### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by sosiristseng**
I tried to replicate the workflow described in `travis.yml`. 
Although IMHO it is simpler to use `tectonic` as the LaTeX engine (no need to juggle TeX packages dependencies), the (possibly breaking) change should go to another PR.

### CODE REVIEW

**Comment by Wandmalfarbe** [comment]
That looks great! Thank you for your contribution. I have no experience with GitHub actions, so I will merge this and see how it goes.

**Comment by cagix** [comment]
> I tried to replicate the workflow described in `travis.yml`. 
> 
> Although IMHO it is simpler to use `tectonic` as the LaTeX engine (no need to juggle TeX packages dependencies), the (possibly breaking) change should go to another PR.

wouldn't it be easier to use `pandoc/latex` (https://github.com/pandoc/dockerfiles) as base-image?

**Comment by Wandmalfarbe** [comment]
> > I tried to replicate the workflow described in `travis.yml`.
> > Although IMHO it is simpler to use `tectonic` as the LaTeX engine (no need to juggle TeX packages dependencies), the (possibly breaking) change should go to another PR.
> 
> wouldn't it be easier to use `pandoc/latex` (https://github.com/pandoc/dockerfiles) as base-image?

I would love to compile with different PDF engines. I believe Docker is the right direction, but I don't know anything about Docker to implement this.

**Comment by Wandmalfarbe** [comment]
I just noticed a bug that may have to do with the introduction of GitHub pages (or recent changes in the package `awesomebox` or the filter `pandoc-latex-environment`). Please have a look at #268.

**Pull request merged**
