### PR TITLE
fix: Merge changes from pandoc 3.1.8 LaTeX template

### PR DESCRIPTION
**Pull request by davidmehren**
Fixes https://github.com/Wandmalfarbe/pandoc-latex-template/issues/361

See https://github.com/jgm/pandoc/compare/3.1.7...3.1.8

### CODE REVIEW

**Comment by cryptax** [comment]
Nice - it works fine in my case :)

**Comment by dm5n** [comment]
Worked for me too, thanks.

Pandoc has been updated to 3.1.9 – will this fix still work?

**Comment by motorto** [comment]
Saved my life dude, thanks working fine here. Appreciate your work !

**Comment by Wandmalfarbe** [comment]
Thanks a lot for your work! I will prepare a regular release soon.

**Pull request merged**
