### PR TITLE
improve footnotes:

### PR DESCRIPTION
**Pull request by salim-b**
- improve footnote formatting using package `footmisc`

    to give an impression, here's a page containing some extensive footnotes in the **old formatting**:
    
    old
    
    and here's the same page with the **new improved formatting**:
    
    new

- make the references from the footnotes at the bottom of the page into links back to the occurence of the footnotes in the main text and introduce an option `disable-footnote-backlinks` to disable this new behaviour.

plus harmonize spacing in the README file

### CODE REVIEW

**Comment by salim-b** [comment]
I just realized that the use of `\usepackage{footnotebackref}` (to reate footnote reference backlinks) is incompatible with the current solution to `Allow footnotes in longtable head/foot`, i.e. [these two lines](https://github.com/Wandmalfarbe/pandoc-latex-template/blob/d88a85d54729d19b0955ac5224e251c88f70643f/eisvogel.tex#L351):

```latex
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
```

As soon as my document contains a table, the following error occurs:

```
Error producing PDF.
! File ended while scanning use of \@tempa.
<inserted text> 
                \par 
l.133 \makesavenoteenv
```

When I comment out the two lines mentioned above, the error disappears.

Any idea how to properly fix this?

**Comment by Wandmalfarbe** [comment]
Thank you for that contribution! I'm a bit busy at the moment so it might take some time for me to review your PR.

**Comment by salim-b** [comment]
> I'm a bit busy at the moment so it might take some time for me to review your PR.

Sure, take your time! :)

What else just came to my mind regarding this PR: Do you think it would make sense to make the improved footnote formatting using package `footmisc` optional, too? I.e. introducing another template variable like `footnotes_pretty`?

**Comment by Wandmalfarbe** [comment]
> What else just came to my mind regarding this PR: Do you think it would make sense to make the improved footnote formatting using package `footmisc` optional, too? I.e. introducing another template variable like `footnotes_pretty`?

Yes, thats a nice Idea.

**Comment by salim-b** [comment]
> Yes, thats a nice Idea.

Ok. Do you have any objections against making  `footnotes_pretty: true` the default?

**Comment by Wandmalfarbe** [comment]
I would propably make the default value `false` because it requires the additional package `footmisc` and adds lots of spacing to footnotes.

**Comment by salim-b** [comment]
> I would propably make the default value `false` because it requires the additional package `footmisc` and adds lots of spacing to footnotes.

Ok, done:)

**Pull request merged**
