### PR TITLE
Add "toc-title" variable support

### PR DESCRIPTION
**Pull request by LeoOnTheEarth**
We can change toc title by setting the `toc-title` variable

For example:

```markdown
---
title: doc title
toc: true
toc-title: Summary
---
```

### CODE REVIEW

**Comment by Wandmalfarbe** [comment]
Thank you for your contribution! Could you please add the variable and a short description to the readme in the section *Custom Template Variables*?

**Comment by LeoOnTheEarth** [comment]
`toc-title` is a variable that provided by pandoc (https://pandoc.org/MANUAL.html#variables-set-by-pandoc)

How about add an example to describe the function of `toc-title` variable?

**Comment by Wandmalfarbe** [comment]
> toc-title is a variable that provided by pandoc (https://pandoc.org/MANUAL.html#variables-set-by-pandoc)

Yea, but it does not work with latex/PDF for now. Maybe you could add the `toc-title` variable to the [pandoc default latex template](https://github.com/jgm/pandoc/blob/master/data/templates/default.latex) instead of this one. I will then merge the changes from pandoc into this repository.

**Comment by Wandmalfarbe** [comment]
Support for `toc-title` has landed in pandoc master with commit https://github.com/jgm/pandoc/commit/dac85d683feb6f9f7e12b9273f353a1291171cd1 and was merged to this repo via commit https://github.com/Wandmalfarbe/pandoc-latex-template/commit/23a97eaf0db1df68f50102820aff6160bf1ae7b2. 

Thank you for this pull request!

**Pull request closed without merging**
