### PR TITLE
adding \pandocbounded macro for pandoc 3.2.1

### PR DESCRIPTION
**Pull request by jvsteiner**

### CODE REVIEW

**Comment by Wandmalfarbe** [comment]
Thank you for this PR. I will be working on a release shortly.

**Comment by simondueckert** [comment]
Cool! Do you know roughly when the working version will bei available in pandoc/extra docker image?

**Comment by Wandmalfarbe** [comment]
@simondueckert This fix is included in [version 2.5.0](https://github.com/Wandmalfarbe/pandoc-latex-template/releases/tag/v2.5.0).

**Comment by galbacarys** [comment]
Hey @Wandmalfarbe  - I am still seeing `Undefined control sequence. \pandocbounded` in the latest version of the docker image. Is there any chance this fix can be pushed into the docker image? I think that's what @simondueckert was asking about as well.

**Pull request merged**
