### PR TITLE
Fix #268: NoValue error in awesomebox example

### LINKED ISSUE #268: Example `boxes-with-pandoc-latex-environment-and-awesomebox` displays `-NoValue-`
The Example `boxes-with-pandoc-latex-environment-and-awesomebox` changed significantly in commit 3b91566da21ccdb3e4cbf0897228dc8b73405a67. There is `-NoValue-` inserted after the `awesomebox` icon, which is undesired.

This may be a result of the addition of GitHub actions (#267) and the PDF generation with that workflow.

preview

### PR DESCRIPTION
**Pull request by sosiristseng**
Fix #268

### CODE REVIEW

**Comment by Wandmalfarbe** [comment]
```
tlmgr install: package array not present in repository.
tlmgr install: package xparse not present in repository.
```

https://tex.stackexchange.com/a/341811

These files are not packages but part of other packages. I believe `array` and `xparse` are part of LaTeX.

**Comment by sosiristseng** [comment]
YOu are right,

- `array` is in `tools` bundle. (https://www.ctan.org/pkg/array)
- `xparse` is in `l3packages` bundle (ctan.org/pkg/xparse)

So they are likely in the base install already.

**Comment by sosiristseng** [comment]
I checked the [build artifact](https://github.com/Wandmalfarbe/pandoc-latex-template/suites/4349282019/artifacts/114119649). The issue is still there.

preview

**Comment by Wandmalfarbe** [comment]
I believe this error is not introduced by your addition of GitHub Actions. Feel free to dig around, but please don't feel obliged to fix it.

**Comment by sosiristseng** [comment]
This might be LaTeX engine-dependent. [The one](https://ntumitolab.github.io/template-pandoc-tectonic/#boxes-awesomebox) I built using `tectonic` a few hours ago (which is based on xelatex) had no such issue.

**Comment by sosiristseng** [comment]
> This might be LaTeX engine-dependent. [The one](https://ntumitolab.github.io/template-pandoc-tectonic/#boxes-awesomebox) I built using `tectonic` a few hours ago (which is based on xelatex) had no such issue.

Switching to xelatex engine for the awesomebox example does not help.

**Pull request closed without merging**
